### ISSUE TITLE
rails asset pipeline integration

### ISSUE THREAD

**Issue by goosetav** [duosecurity/duo_ruby#10]
currently the js files are just stuffed into the top-level of the gem. Since the gem seems to be targeting rails apps and not just plain ruby, please add the integrations to allow the javascript files to be used via the asset pipeline

see http://guides.rubyonrails.org/asset_pipeline.html#adding-assets-to-your-gems for reference

**Comment by AaronAtDuo** [comment]
Closing out this old issue
