### ISSUE TITLE
Gemification

### ISSUE THREAD

**Issue by TheKidCoder** [duosecurity/duo_ruby#3]
I have started work on a gemified version of this repo here: https://github.com/TheKidCoder/duo-auth

I think the ruby community (myself included) is pretty adverse to relying on single file dependencies. As such, gemification is the way to go.

I am happy to maintain the gem and am going to be adding some rails features to it that will automatically embed the iFrame auth system. Also looking to add automatic bindings for gems like devise.

I would be willing to add someone from Duo as a committer to the duo-auth gem as well. Let me know your thoughts!

**Comment by TheKidCoder** [comment]
Any update here?

**Comment by mschwager** [comment]
The @TheKidCoder, sorry for such a long delay in responding. I agree that this would be a great feature to have, but it's currently low priority for us. We'll keep an eye on it and get around to it when we've got time :)

**Comment by TheKidCoder** [comment]
Not sure what you mean by feature? This gem has been used in production for a while now, https://rubygems.org/gems/duo-auth

I'm more so suggesting just replacing this repo with the gem version.

**Comment by happymcplaksin** [comment]
An official Gem from Duo would be ideal.

It's great that Duo provides code for Ruby. But it would be even better if it was a normal Gem and thus easier for folks to use.

Thanks!

**Comment by TheKidCoder** [comment]
I've been using the gem I published in production for a while now. Even though its not official, I keep it current with this repo.

**Comment by mschwager** [comment]
Finally got around to this: https://rubygems.org/gems/duo_web

Cheers!
