### ISSUE TITLE
Ruby 2.2.3 requires a switch from Digest::HMAC to OpenSSL::HMAC

### ISSUE THREAD

**Issue by nchelluri** [duosecurity/duo_ruby#4]
Very similar to this issue in another project: https://github.com/emartech/escher-ruby/issues/5

Basically, Ruby 2.2.3 doesn't have the Digest::HMAC class.

From http://ruby-doc.org//stdlib-1.9.3/libdoc/digest/rdoc/Digest/HMAC.html:

> CAUTION: Use of this library is discouraged, because this implementation was meant to be experimental but somehow got into the 1.9 series without being noticed. Please use OpenSSL::HMAC in the “openssl” library instead.

So we need to switch to using the OpenSSL HMAC class instead.

**Comment by nchelluri** [comment]
Wrong repo. Meant to add this to https://github.com/duosecurity/duo_api_ruby .

**Comment by TheKidCoder** [comment]
@nchelluri This is still a valid issue. Thanks for bringing it up.
I personally discourage use of https://github.com/duosecurity/duo_api_ruby because they still haven't turned their ruby implementation into a gem...

**Comment by nchelluri** [comment]
I do agree with your thinking about the lack of a gem, but I am pretty sure this repo uses OpenSSL instead of Digest.

**Comment by mschwager** [comment]
Thanks for the heads up!

I'll take a look at the PR on https://github.com/duosecurity/duo_api_ruby :)
